# Generated by Django 5.1.7 on 2025-05-01 17:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'ordering': ['ordinal', '-created']},
        ),
        migrations.RemoveField(
            model_name='projects',
            name='description',
        ),
        migrations.AddField(
            model_name='projects',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='link',
            field=models.URLField(default=12, help_text='URL to the live project or demo', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='results',
            field=models.JSONField(default=list, help_text="List of result objects, e.g. [{ 'title': '…' }, …]"),
        ),
        migrations.AddField(
            model_name='projects',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='company',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=models.URLField(help_text='URL of the project image', max_length=500),
        ),
        migrations.AlterField(
            model_name='projects',
            name='ordinal',
            field=models.IntegerField(default=0, help_text='Sort order'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='projects',
            name='year',
            field=models.CharField(max_length=4),
        ),
    ]
