# Generated by Django 5.1.7 on 2025-05-08 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0002_alter_projects_options_remove_projects_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
